### ISSUE TITLE
Disclaimer consideration

### ISSUE THREAD

**Issue by danzek** [dlcowen/CanIPayTheRansom#6]
I'd add a disclaimer to the effect:

>This website is provided "as is" without warranty of any kind, express or implied, including but not limited to the warranties of merchantability, fitness for a particular purpose and noninfringement. In no event shall the authors or copyright holders be liable for any claim, damages, sanctions, or other liability, whether in an action of contract, tort or otherwise, arising from, out of or in connection with the website or the use or other dealings in the website. There is no guarantee of accuracy.

This is not legal advice. This is just an idea for your consideration.

**Comment by dlcowen** [comment]
Great point
